package controllers_test

import "net/http"

var groupControllerTests = []*requestTest{
	{
		"Get the average temperature detected by sensors in a group 'StatusOK'",
		"/api/v1/group/gamma/temperature/average",
		"GET",
		``,
		http.StatusOK,
		`(\d+\.\d+)`,
		"wrong sensors group average temperature request",
	},
	{
		"Get the average temperature detected by sensors in a group 'StatusInternalServerError'",
		"/api/v1/group/dggd/temperature/average",
		"GET",
		``,
		http.StatusInternalServerError,
		`{"error":"upper: no more rows in this result set"}`,
		"wrong sensors group average temperature request",
	},
	{
		"Get the average transparency detected by sensors in a group 'StatusOK'",
		"/api/v1/group/gamma/transparency/average",
		"GET",
		``,
		http.StatusOK,
		`(\d+\.\d+)`,
		"wrong sensors group average transparency request",
	},
	{
		"Get the average transparency detected by sensors in a group 'StatusInternalServerError'",
		"/api/v1/group/dggd/transparency/average",
		"GET",
		``,
		http.StatusInternalServerError,
		`{"error":"upper: no more rows in this result set"}`,
		"wrong sensors group average transparency request",
	},
	{
		"Get fish species in a group 'StatusOK'",
		"/api/v1/group/gamma/species",
		"GET",
		``,
		http.StatusOK,
		`{"name":\s*".*?",\s*"count":\s*\d+}`,
		"wrong sensors group fish species request",
	},
	{
		"Get fish species in a group 'StatusInternalServerError'",
		"/api/v1/group/dggd/species",
		"GET",
		``,
		http.StatusInternalServerError,
		`{"error":"upper: no more rows in this result set"}`,
		"wrong sensors group fish species request",
	},
	{
		"Get top fish species in a group 'StatusOK'",
		"/api/v1/group/gamma/species/top/2",
		"GET",
		``,
		http.StatusOK,
		`\[(?:{"name":\s*".*?",\s*"count":\s*\d+},?){2}\]`,
		"wrong sensors group top fish species request",
	},
	{
		"Get top fish species in a group 'StatusMovedPermanently'",
		"/api/v1/group/gamma/species/top/",
		"GET",
		``,
		http.StatusMovedPermanently,
		`<a href="/api/v1/group/gamma/species/top">Moved Permanently</a>`,
		"wrong sensors group fish species request",
	},
	//{
	//	"Get top fish species in a group 'StatusBadRequest'",
	//	"/api/v1/group/gamma/species/top/df",
	//	"GET",
	//	``,
	//	http.StatusBadRequest,
	//	`{"error":"strconv.ParseInt: parsing \"df\": invalid syntax"}`,
	//	"wrong sensors group fish species request",
	//},
	{
		"Get top fish species in a group 'StatusInternalServerError'",
		"/api/v1/group/dgdg/species/top/2",
		"GET",
		``,
		http.StatusInternalServerError,
		`{"error":"upper: no more rows in this result set"}`,
		"wrong sensors group fish species request",
	},
	{
		"Get top fish species in a group from/till 'StatusOK'",
		"/api/v1/group/gamma/species/top/2?from=1634764800&till=1698058383",
		"GET",
		``,
		http.StatusOK,
		`\[(?:{"name":\s*".*?",\s*"count":\s*\d+},?){2}\]`,
		"wrong sensors group top fish species from/till request",
	},
	{
		"Get top fish species in a group from/till 'StatusBadRequest'",
		"/api/v1/group/gamma/species/top/2?from=h&till=h",
		"GET",
		``,
		http.StatusBadRequest,
		`{"error":"from parameter is not a valid UNIX timestamp"}`,
		"wrong sensors group top fish species from/till request",
	},
}
